/**
 * Traced silhouette of public/lenny-nobackground.png — up the left shoulder,
 * through the neck, around the jaw and hair, back down the right shoulder.
 *
 * NOT hand-drawn, and not a top-edge sketch either. Generated by decoding the
 * PNG's alpha channel and running a Moore-neighbour boundary trace over the
 * binarised mask, so it follows the REAL contour — including the concave notch
 * where the neck meets the shoulder, which a "topmost opaque pixel per column"
 * scan structurally cannot see. Border runs (where the crop cuts the shoulders
 * off at the image edge) are dropped, then the remaining run is lightly
 * smoothed, simplified with Douglas-Peucker, and fitted with Catmull-Rom
 * beziers whose handles are clamped to each segment's box (unclamped handles
 * throw a visible spike wherever the outline runs near-vertical).
 *
 * Verified fit against the true boundary: mean 0.55px, max 3.30px on a 500px
 * wide source.
 *
 * Coordinates are in the PNG's own 500x500 space, so the overlay SVG uses
 * viewBox="0 0 500 500" with preserveAspectRatio="xMidYMax meet" to match the
 * image's object-contain / object-bottom placement precisely.
 *
 * Regenerate only if the portrait asset changes.
 */
export const SILHOUETTE_PATH =
  "M 32 495.5 C 35.0 485.4, 44.8 451.8, 50.3 435 C 55.8 418.3, 59.9 406.2, 64.7 395 C 69.5 383.8, 73.5 376.8, 79 368 C 84.5 359.2, 93.2 347.7, 98 342 C 102.8 336.3, 98.0 340.9, 108 333.9 C 125.2 326.9, 184.7 306.2, 201 299.9 C 206.1 296.0, 205.3 297.3, 206.1 296 C 206.1 294.7, 206.1 296.0, 205.7 292 C 202.3 284.8, 190.2 263.8, 186 253 C 181.8 242.2, 181.9 231.8, 180.6 227 C 179.3 224.4, 179.9 225.3, 178 224.4 C 176.1 223.5, 171.5 223.1, 169.1 221.7 C 166.7 220.3, 166.5 221.7, 163.7 216 C 160.9 209.9, 153.8 190.7, 152.3 185 C 152.3 181.9, 152.3 183.2, 155 181.9 C 158.4 180.6, 168.5 180.6, 172.6 177.1 C 176.7 173.6, 178.3 164.5, 179.4 161 C 179.4 157.5, 179.4 161.0, 179.1 156 C 177.4 151.0, 170.4 139.8, 169 131 C 169.0 122.2, 169.3 108.9, 170.7 103.4 C 172.0 98.0, 173.2 103.1, 177.1 98 C 181.0 92.9, 189.1 77.9, 194.1 72.6 C 199.1 67.3, 202.7 67.6, 207 66.4 C 211.3 65.6, 217.2 66.4, 219.9 65.6 C 222.6 64.5, 220.9 61.9, 223.1 60 C 225.3 58.1, 228.2 55.3, 233 54.1 C 237.8 53.0, 247.2 53.8, 252 53 C 256.8 52.3, 258.5 50.4, 262 49.6 C 265.5 48.8, 266.0 48.4, 273 48.4 C 280.0 49.4, 295.3 52.7, 304 55.9 C 312.7 59.1, 319.3 64.7, 325 67.4 C 330.7 70.1, 335.1 70.6, 338 72 C 340.9 73.4, 340.4 73.3, 342.7 76 C 345.0 78.7, 349.2 82.7, 351.7 88 C 354.2 93.3, 357.6 102.0, 357.9 108 C 357.9 114.0, 353.9 117.7, 353.6 124 C 353.6 130.3, 356.2 139.3, 356.4 146 C 356.4 152.7, 356.2 153.8, 355 164 C 353.8 174.2, 352.0 194.3, 349.3 207 C 346.6 219.7, 340.8 232.7, 338.7 240 C 337.0 247.3, 337.1 247.5, 337 251 C 337.0 254.5, 337.0 257.7, 338.3 261 C 340.1 264.3, 343.2 265.3, 347.6 271 C 352.1 276.7, 347.6 283.5, 365 295.3 C 384.9 307.1, 447.9 332.7, 467 341.7 C 479.7 349.4, 474.9 344.8, 479.7 349.4 C 484.5 354.0, 493.3 366.1, 496 369.5";

/** Native pixel dimensions the path was traced against. */
export const SILHOUETTE_VIEWBOX = "0 0 500 500";
